language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
addons:
  apt:
    packages:
      gradle
before_script:
  - mkdir dependences
  - wget http://github.com/erpcya/adempiere/releases/latest/download/Adempiere_393LTS.tar.gz -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/Adempiere.jar dependences/Adempiere.jar
  - mv Adempiere/packages/FixedAssetManagement/lib/FixedAssetManagement.jar dependences/FixedAssetManagement.jar
jobs:
  include:
    - stage: Compilation
      script: ./gradlew build
    - stage: Prepare Release
      script:
         - ./gradlew build 
         - ./gradlew release
      on:
       tags: true
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  skip_cleanup: true
  file: 
    - "$TRAVIS_BUILD_DIR/build/release/EnterpriseAssetMaintenance.zip"
  on:
    tags: true