language: java
jdk:
- openjdk8
install: gradle wrapper
os:
- linux
sudo: required
before_install:
  - wget https://services.gradle.org/distributions/gradle-6.1.1-bin.zip
  - unzip -qq gradle-6.1.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.1.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
before_script:
  - mkdir dependences
  - wget http://github.com/erpcya/adempiere/releases/latest/download/Adempiere_393LTS.tar.gz -c -O Adempiere.tar.gz
  - tar -xzf Adempiere.tar.gz
  - mv Adempiere/lib/Adempiere.jar dependences/Adempiere.jar
  - mv Adempiere/packages/FixedAssetManagement/lib/FixedAssetManagement.jar dependences/FixedAssetManagement.jar
jobs:
  include:
    - stage: Compilation
      script: gradle build
    - stage: Prepare Release
      script: 
         - gradle createRelease
      on:
       tags: true
deploy:
  provider: releases
  token: $GITHUB_TOKEN_KEY
  skip_cleanup: true
  file: 
    - "$TRAVIS_BUILD_DIR/build/release/EnterpriseAssetMaintenance.zip"
    - "$TRAVIS_BUILD_DIR/build/release/EnterpriseAssetMaintenance.zip.MD5"
  on:
    tags: true